channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.10
  - bioconda::java-jdk=8.0.112
  - pip
  - pip:
    - pyodbc==4.0.31
    - pyarrow==4.0.1
    - JPype1==1.3.0
    - JayDeBeApi==1.2.3
    - pyspark==3.1.2
    - pandas==1.3.0
    - xlrd3==1.1.0
    - jupyterlab==3.0.16