from pyspark.sql.types import StructField,StructType,StringType,IntegerType,DateType,DecimalType,FloatType

def get_table_schema():
  try:
    project_schema = \
      StructType([
        StructField('ID',IntegerType(),True),
        StructField('QuoteID',StringType(),True),
        StructField('ProjectID',StringType(),True),
        StructField('DateCreated',DateType(),True),
        StructField('SignedQuoteReceived',StringType(),True),
        StructField('DateSamplesReceived',StringType(),True),
        StructField('SampleReceived',StringType(),True),
        StructField('LegacyProjectID',StringType(),True),
        StructField('Initial_QC',StringType(),True),
        StructField('Number_of_items_for_Initial_QC',StringType(),True),
        StructField('IQC_Unit_price',StringType(),True),
        StructField('Library_Preparation',StringType(),True),
        StructField('Number_of_items_for_Library_Prep',StringType(),True),
        StructField('LP_Unit_price',StringType(),True),
        StructField('Library_QC',StringType(),True),
        StructField('Number_of_items_for_Library_QC',StringType(),True),
        StructField('LQC_Unit_price',StringType(),True),
        StructField('Sequencing_Type',StringType(),True),
        StructField('Number_of_Lanes',StringType(),True),
        StructField('Seq_Unit_price',StringType(),True),
        StructField('Data_analysis',StringType(),True),
        StructField('Number_of_items_for_Data_Analysis',StringType(),True),
        StructField('DA_Unit_price',StringType(),True),
        StructField('Total_Quoted',StringType(),True),
        StructField('Price_Band',StringType(),True),
        StructField('Cost_of_Project',StringType(),True),
        StructField('estimated_surplus',StringType(),True),
        StructField('ProjectSummary',StringType(),True),
        StructField('VAT',StringType(),True),
        StructField('Grant Code',StringType(),True),
        StructField('Issued',StringType(),True),
        StructField('ProjectTag',StringType(),True),
        StructField('Comments',StringType(),True),
        StructField('Status',StringType(),True),
        StructField('Customer Note',StringType(),True),
        StructField('Library QC_summary',StringType(),True),
        StructField('Sequencing_summary',StringType(),True),
        StructField('Data Analysis_summary',StringType(),True),
        StructField('Misc_summary',StringType(),True),
        StructField('Misc1',StringType(),True),
        StructField('Misc1_description',StringType(),True),
        StructField('Misc1_qty',StringType(),True),
        StructField('Misc1_unitprice',StringType(),True),
        StructField('Instrument Access',StringType(),True),
        StructField('InsAcc_description',StringType(),True),
        StructField('InsAcc_qty',StringType(),True),
        StructField('InsAcc_unitprice',StringType(),True),
        StructField('Main_contact',StringType(),True),
        StructField('Main_contact_email',StringType(),True)])
    sample_schema = \
      StructType([
        StructField('ID',IntegerType(),True),
        StructField('ProjectID',IntegerType(),True),
        StructField('IGFID',StringType(),True),
        StructField('Container ID',StringType(),True),
        StructField('Well position',StringType(),True),
        StructField('Sample number',StringType(),True),
        StructField('Sample Name',StringType(),True),
        StructField('Sample type',StringType(),True),
        StructField('Species',StringType(),True),
        StructField('Sample description',StringType(),True),
        StructField('Volume (ul)',StringType(),True),
        StructField('Diluent',StringType(),True),
        StructField('Concentration (ng/ul)',StringType(),True),
        StructField('Quantification method',StringType(),True),
        StructField('Bionalyzer trace provided',StringType(),True),
        StructField('RIN value',StringType(),True),
        StructField('DNAse treated?',StringType(),True),
        StructField('Pool number',StringType(),True),
        StructField('Workflow',StringType(),True),
        StructField('Status',StringType(),True),
        StructField('Concentration (ng/ul) -internal value',StringType(),True),
        StructField('Trace file',StringType(),True),
        StructField('ContainerType',StringType(),True),
        StructField('SampleQCPass',StringType(),True)])
    library_schema = \
      StructType([
        StructField("ID",IntegerType(),True),
        StructField("ProjectID",IntegerType(),True),
        StructField("Container_ID",StringType(),True),
        StructField("Well_Position",StringType(),True),
        StructField("Library_Name",StringType(),True),
        StructField("Library_Type",StringType(),True),
        StructField("Library_Prep_Kit_Manufacturer",StringType(),True),
        StructField("Library_Prep_Kit_Name",StringType(),True),
        StructField("Library_Prep_Kit_Catalogue_No",StringType(),True),
        StructField("Index_1_ID",StringType(),True),
        StructField("Index1_Sequence",StringType(),True),
        StructField("Index1_Length",StringType(),True),
        StructField("Index_2_ID",StringType(),True),
        StructField("Index2_Sequence",StringType(),True),
        StructField("Index_2_Length",StringType(),True),
        StructField("Library_Volume_ul",StringType(),True),
        StructField("Library_Average_Fragment_Size_bp",StringType(),True),
        StructField("Library_Concentration_ng/ul",StringType(),True),
        StructField("nM_library",StringType(),True),
        StructField("Pool_No",StringType(),True),
        StructField("Spike-in_PhiX_PCT",StringType(),True),
        StructField("Read_1_Primer_name",StringType(),True),
        StructField("Read_2_Primer_name",StringType(),True),
        StructField("Index_1_Primer_name",StringType(),True),
        StructField("Index_2_Primer_name",StringType(),True),
        StructField("Volume_ul_Pool",StringType(),True),
        StructField("Pool_Average_Fragment_Size_bp",StringType(),True),
        StructField("Pool_Concentration_ng/ul",StringType(),True),
        StructField("Pool_nM",StringType(),True),
        StructField("Premade",StringType(),True),
        StructField("Status",StringType(),True),
        StructField("Workflow",StringType(),True),
        StructField("ContainerType",StringType(),True),
        StructField("Species",StringType(),True),
        StructField("LIbraryID",StringType(),True)])
    quotes_schema = \
      StructType([
        StructField('CustomerID',StringType(),True),
        StructField('QuoteID', StringType(),True),
        StructField('Initial_QC', StringType(),True),
        StructField('Number_of_items_for_Initial_QC',StringType(),True),
        StructField('IQC_Unit_price', StringType(),True),
        StructField('Library_Preparation',StringType(),True),
        StructField('Number_of_items_for_Library_Prep', StringType(),True),
        StructField('LP_Unit_price', StringType(),True),
        StructField('Library_QC',StringType(),True),
        StructField('Number_of_items_for_Library_QC',StringType(),True), 
        StructField('LQC_Unit_price', StringType(),True),
        StructField('Sequencing_Type',StringType(),True),
        StructField('Number_of_Lanes', FloatType(),True),
        StructField('Seq_Unit_price', StringType(),True),
        StructField('Data_analysis',StringType(),True),
        StructField('Number_of_items_for_Data_Analysis',StringType(),True), 
        StructField('DA_Unit_price', StringType(),True),
        StructField('Total_Quoted',StringType(),True),
        StructField('Price_Band',StringType(),True),
        StructField('Cost_of_Project', StringType(),True),
        StructField('estimated_surplus', StringType(),True),
        StructField('ProjectSummary',StringType(),True),
        StructField('VAT',StringType(),True),
        StructField('Grant Code', StringType(),True),
        StructField('Issued', StringType(),True),
        StructField('ProjectTag', StringType(),True),
        StructField('Comments', StringType(),True),
        StructField('Status',StringType(),True),
        StructField('Customer Note', StringType(),True),
        StructField('Instrument Access', StringType(),True),
        StructField('InsAcc_description',StringType(),True),
        StructField('InsAcc_qty',StringType(),True),
        StructField('InsAcc_unitprice',StringType(),True),
        StructField('QC',StringType(),True),
        StructField('Library Preparation', StringType(),True),
        StructField('QC.1',StringType(),True),
        StructField('Sequencing',StringType(),True),
        StructField('Data Analysis',StringType(),True),
        StructField('Misc',StringType(),True),
        StructField('Misc1',StringType(),True),
        StructField('Misc1_description',StringType(),True),
        StructField('Misc1_qty',StringType(),True),
        StructField('Misc1_unitprice',StringType(),True),
        StructField('Main_contact',StringType(),True),
        StructField('Main_contact_email',StringType(),True)])
    return project_schema,sample_schema,library_schema,quotes_schema
  except Exception as e:
    raise ValueError('Failed to fetch table schema, error: {0}'.format(e))